workflows:
  ios_nosign:
    name: Build iOS App Without Signing
    max_build_duration: 60  # 最大构建时长，单位为分钟
    actions:
      - name: Install dependencies
        script:
          - gem install fastlane # 安装 fastlane（如果需要）
      
      - name: Build the iOS app
        script:
          - xcodebuild -project TaskPortHaxxApp.xcodeproj -scheme TaskPortHaxxApp -configuration Release clean build CODE_SIGNING_REQUIRED=NO

      - name: Export .ipa
        script:
          - xcodebuild -exportArchive -archivePath build/ios/TaskPortHaxxApp.xcarchive -exportPath build/ios/ipa/ -exportOptionsPlist ExportOptions.plist
